var1 = int(raw_input("Enter integer 1 :"))
var2 = int(raw_input("Enter integer 2 :"))
print "%d + %d = %d" % (var1, var2, var1 + var2)
print "%d * %d = %d" % (var1, var2, var1 * var2)
print "%d / %d = %f" % (var1, var2, var1 / float(var2))
